algoritmo "MaiorOuMenor"
var
   nome: caractere
   num_A, num_B: inteiro
inicio
      EscrevaL("----------------------------------------------------------------------")
      EscrevaL("                 Olá, seja bem vindx ao Mathematicando!               ")
      EscrevaL("Meu nome é Kaytlhin Mariah e estou aqui para te ajudar a mathematicar!")
      EscrevaL("                    Desculpe pelo trocadilho ruim xD")
      EscrevaL("----------------------------------------------------------------------")
      EscrevaL("  ")
      EscrevaL("  ")
      EscrevaL("Digite o seu nome:")
      Leia (nome)
      EscrevaL("Digite um número:")
      Leia(num_A)
      EscrevaL("Digite outro número:")
      Leia(num_B)
      EscrevaL("  ")
      EscrevaL("  ")
      EscrevaL("--------------------------------DADOS---------------------------------")
      EscrevaL("O primeiro número escolhido foi: ", num_A)
      EscrevaL("O segundo  número escolhido foi: ", num_B)
      EscrevaL("----------------------------------------------------------------------")
      EscrevaL("  ")
      EscrevaL("  ")
      EscrevaL("-----------------------------RESULTADOS-------------------------------")
      Escreva(Num_A," é maior que",num_B,"?")
      EscrevaL(num_A > num_B)
      EscrevaL("----------------------------------------------------------------------")
fimalgoritmo

